Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2022-09, with the labels that each got.

#79 Add interface to purge audit logs
  src/main/java/com/czertainly/api/interfaces/core/web/AuditLogController.java
Labels: enhancement

#80 Fix return code and content for audit logs purge
  src/main/java/com/czertainly/api/interfaces/core/web/AuditLogController.java
Labels: bug, ignore-for-release

#81 Add description to compliance profile list dto
  src/main/java/com/czertainly/api/model/core/compliance/ComplianceProfilesListDto.java
Labels: bug

#82 Add attributes to the compliance results of the certificate
  src/main/java/com/czertainly/api/model/core/certificate/CertificateComplianceResultDto.java
Labels: enhancement

#84 Release/1.4.0
  pom.xml
  src/main/java/com/czertainly/api/interfaces/core/web/AcmeProfileController.java
  src/main/java/com/czertainly/api/interfaces/core/web/AuditLogController.java
  src/main/java/com/czertainly/api/interfaces/core/web/AuthorityInstanceController.java
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/interfaces/core/web/ClientManagementController.java
  src/main/java/com/czertainly/api/interfaces/core/web/ComplianceProfileController.java
  src/main/java/com/czertainly/api/interfaces/core/web/ConnectorController.java
  src/main/java/com/czertainly/api/interfaces/core/web/CredentialController.java
  src/main/java/com/czertainly/api/model/client/connector/ForceDeleteMessageDto.java
  src/main/java/com/czertainly/api/model/client/dashboard/StatisticsDto.java
  src/main/java/com/czertainly/api/model/common/BulkActionMessageDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateComplianceResultDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
  src/main/java/com/czertainly/api/model/core/compliance/ComplianceConnectorAndGroupsDto.java
  src/main/java/com/czertainly/api/model/core/compliance/ComplianceGroupsDto.java
  src/main/java/com/czertainly/api/model/core/raprofile/RaProfileDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchLabelConstants.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: ignore-for-release

#85 Release/1.4.0
  pom.xml
Labels: ignore-for-release

#89 Update summary of the API for documentation
  src/main/java/com/czertainly/api/interfaces/connector/entity/EntityController.java
  src/main/java/com/czertainly/api/interfaces/connector/entity/LocationController.java
  src/main/java/com/czertainly/api/interfaces/core/web/EntityInstanceController.java
  src/main/java/com/czertainly/api/interfaces/core/web/LocationManagementController.java
Labels: documentation

#90 Update interface summary for API documentation
  src/main/java/com/czertainly/api/interfaces/connector/entity/EntityController.java
  src/main/java/com/czertainly/api/interfaces/connector/entity/LocationController.java
  src/main/java/com/czertainly/api/interfaces/core/web/EntityInstanceController.java
  src/main/java/com/czertainly/api/interfaces/core/web/LocationManagementController.java
Labels: documentation
