Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2022-12, with the labels that each got.

#122 Update metadata response source object from UUID to Name and UUID
  src/main/java/com/czertainly/api/model/client/metadata/ResponseMetadataDto.java
Labels: enhancement, ignore-for-release

#124 Equals and Hashcode functions for Attribute Contents
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/AttributeContentType.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/BaseAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/BooleanAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/CredentialAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/DateAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/DateTimeAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/FileAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/FloatAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/IntegerAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/ObjectAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/SecretAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/StringAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/TextAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/TimeAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/FileAttributeContentData.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/SecretAttributeContentData.java
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
Labels: enhancement

#126 Mask Secret for Response Attribute DTOs
  src/main/java/com/czertainly/api/config/serializer/ResponseAttributeSerializer.java
  src/main/java/com/czertainly/api/model/client/attribute/ResponseAttributeDto.java
  src/main/java/com/czertainly/api/model/client/attribute/metadata/GlobalMetadataCreateRequestDto.java
  src/main/java/com/czertainly/api/model/client/attribute/metadata/GlobalMetadataDefinitionDetailDto.java
  src/main/java/com/czertainly/api/model/client/attribute/metadata/GlobalMetadataUpdateRequestDto.java
  src/main/java/com/czertainly/api/model/client/metadata/ResponseMetadataDto.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/CustomAttribute.java
Labels: enhancement

#129 Correct Audit Logs endpoints query params schema annotations
  src/main/java/com/czertainly/api/interfaces/core/web/AuditLogController.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/DateAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/DateTimeAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/TimeAttributeContent.java
  src/main/java/com/czertainly/api/model/core/audit/AuditLogFilter.java
  src/main/java/com/czertainly/api/model/core/search/SearchCondition.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: documentation

#130 Add endpoint to list objects for permission editor
  src/main/java/com/czertainly/api/interfaces/core/web/AuthController.java
Labels: enhancement

#131 Correct schema and initialize required list of attributes in DTOs
  src/main/java/com/czertainly/api/model/client/authority/AuthorityInstanceRequestDto.java
  src/main/java/com/czertainly/api/model/client/authority/AuthorityInstanceUpdateRequestDto.java
  src/main/java/com/czertainly/api/model/client/compliance/ComplianceProfileRuleDto.java
  src/main/java/com/czertainly/api/model/client/credential/CredentialRequestDto.java
  src/main/java/com/czertainly/api/model/client/credential/CredentialUpdateRequestDto.java
  src/main/java/com/czertainly/api/model/client/discovery/DiscoveryHistoryDetailDto.java
  src/main/java/com/czertainly/api/model/core/authority/AuthorityInstanceDto.java
  src/main/java/com/czertainly/api/model/core/credential/CredentialDto.java
  src/main/java/com/czertainly/api/model/core/entity/EntityInstanceDto.java
  src/main/java/com/czertainly/api/model/core/location/LocationDto.java
  src/main/java/com/czertainly/api/model/core/raprofile/RaProfileDto.java
Labels: bug

#134 Update Credential Attribute Content with New Content Data Type
  src/main/java/com/czertainly/api/config/serializer/ResponseAttributeSerializer.java
  src/main/java/com/czertainly/api/interfaces/core/web/AuditLogController.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/CredentialAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/CredentialAttributeContentData.java
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
  src/main/java/com/czertainly/core/util/V2AttributeMigrationUtils.java
  src/test/java/com/czertainly/util/AttributeDefinitionUtilsTest.java
Labels: enhancement

#135 Add Attribute Constraint Validation
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
  src/test/java/com/czertainly/util/AttributeDefinitionUtilsTest.java
Labels: enhancement

#136 Cryptography Provider support
  pom.xml
  src/main/java/com/czertainly/api/clients/cryptography/CryptographicOperationsApiClient.java
  src/main/java/com/czertainly/api/clients/cryptography/KeyManagementApiClient.java
  src/main/java/com/czertainly/api/clients/cryptography/TokenInstanceApiClient.java
  src/main/java/com/czertainly/api/exception/CryptographicOperationException.java
  src/main/java/com/czertainly/api/exception/KeyManagementException.java
  src/main/java/com/czertainly/api/exception/TokenInstanceException.java
  src/main/java/com/czertainly/api/interfaces/connector/cryptography/CryptographicOperationsController.java
  src/main/java/com/czertainly/api/interfaces/connector/cryptography/KeyManagementController.java
  src/main/java/com/czertainly/api/interfaces/connector/cryptography/TokenInstanceController.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/CryptographicAlgorithm.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/TokenInstanceStatus.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/CreateKeyRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/DestroyKeyRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/KeyDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/CipherDataRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/DecryptDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/EncryptDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/RandomDataRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/RandomDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/SignDataRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/SignDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/SignatureDataRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/VerifyDataRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/VerifyDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/data/CipherRequestData.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/data/CipherResponseData.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/data/SignatureRequestData.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/data/SignatureResponseData.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/data/VerificationResponseData.java
  src/main/java/com/czertainly/api/model/connector/cryptography/token/TokenInstanceDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/token/TokenInstanceRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/token/TokenInstanceStatusComponent.java
  src/main/java/com/czertainly/api/model/connector/cryptography/token/TokenInstanceStatusDto.java
Labels: new-feature

#139 Add cryptography provider function group code
  src/main/java/com/czertainly/api/model/core/connector/FunctionGroupCode.java
Labels: enhancement

#140 Fix attribute content conversion
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
Labels: bug
