Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2022-07, with the labels that each got.

#63 Update attribute utils methods to return consistent data objects
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
Labels: enhancement

#68 Include CertificateOperationException in the v2 CertificateController
  src/main/java/com/czertainly/api/interfaces/connector/v2/CertificateController.java
Labels: enhancement

#69 Fix truststore parsing
  src/main/java/com/czertainly/api/clients/BaseApiClient.java
Labels: bug

#71 Update API method for updating RA Profile to ACME
  src/main/java/com/czertainly/api/interfaces/core/web/AcmeProfileController.java
Labels: bug

#72 Update error message of validate attribute
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
Labels: enhancement, ignore-for-release

#74 fix detected SonarQube bugs
  src/main/java/com/czertainly/api/interfaces/core/acme/AcmeController.java
  src/main/java/com/czertainly/api/interfaces/core/acme/AcmeRaProfileController.java
  src/main/java/com/czertainly/core/util/AttributeMigrationUtils.java
  src/main/java/com/czertainly/core/util/DatabaseMigrationUtils.java
Labels: bug
