Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2022-10, with the labels that each got.

#93 Add fingerprint calculation exceptions to interface
  src/main/java/com/czertainly/api/interfaces/core/client/ClientOperationController.java
  src/main/java/com/czertainly/api/interfaces/core/client/v2/ClientOperationController.java
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
Labels: enhancement

#94 Extend access control functionality
  src/main/java/com/czertainly/api/interfaces/core/web/RoleManagementController.java
  src/main/java/com/czertainly/api/model/core/auth/ObjectPermissionsDto.java
  src/main/java/com/czertainly/api/model/core/auth/ObjectPermissionsRequestDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserRequestDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserUpdateRequestDto.java
Labels: enhancement

#95 Add API for Update user profile
  src/main/java/com/czertainly/api/interfaces/core/web/AuthController.java
Labels: enhancement

#97 Fix user and object permissions DTOs string building
  src/main/java/com/czertainly/api/model/core/auth/ObjectPermissionsDto.java
  src/main/java/com/czertainly/api/model/core/auth/ObjectPermissionsRequestDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserDetailDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserRequestDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserUpdateRequestDto.java
Labels: bug

#99 Compliance Profile Rule as response for adding new rule
  src/main/java/com/czertainly/api/interfaces/core/web/ComplianceProfileController.java
  src/main/java/com/czertainly/api/model/client/compliance/ComplianceProfileRuleDto.java
Labels: enhancement

#102 Update request method from Post to Patch
  src/main/java/com/czertainly/api/interfaces/core/web/ComplianceProfileController.java
  src/main/java/com/czertainly/api/interfaces/core/web/RAProfileManagementController.java
Labels: bug

#103 Add Private Key Flag when pushing the certificate to a location
  src/main/java/com/czertainly/api/model/connector/entity/PushCertificateResponseDto.java
Labels: enhancement, ignore-for-release

#104 Update description for Push Certificate Response DTO
  src/main/java/com/czertainly/api/model/connector/entity/PushCertificateResponseDto.java
Labels: bug

#106 Release/1.5.0
  README.md
  pom.xml
Labels: ignore-for-release
