Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2023-07, with the labels that each got.

#274 Management of internal notification messages
  src/main/java/com/czertainly/api/interfaces/core/web/NotificationController.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationRequestDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationResponseDto.java
Labels: new-feature

#275 Fix annotation of mark notification as read endpoint
  src/main/java/com/czertainly/api/interfaces/core/web/NotificationController.java
Labels: bug, ignore-for-release

#277 Add sending timestamp and target object identification to notification
  src/main/java/com/czertainly/api/model/client/notification/NotificationDto.java
Labels: enhancement, ignore-for-release

#282 Add email property to role DTOs
  src/main/java/com/czertainly/api/model/client/auth/RoleRequestDto.java
  src/main/java/com/czertainly/api/model/core/auth/RoleDto.java
  src/main/java/com/czertainly/api/model/core/auth/RoleRequestDto.java
Labels: enhancement

#276 Interface for management of approvals
  src/main/java/com/czertainly/api/interfaces/core/web/ApprovalController.java
  src/main/java/com/czertainly/api/interfaces/core/web/ApprovalProfileController.java
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalDetailDto.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalDetailStepDto.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalDto.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalResponseDto.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalStatusEnum.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalStepRecipientDto.java
  src/main/java/com/czertainly/api/model/client/approval/UserApprovalDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileForVersionDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalStepDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserProfileDto.java
Labels: new-feature

#283 Update structure of notification messages
  src/main/java/com/czertainly/api/model/connector/notification/NotificationDataScheduledJobCompleted.java
  src/main/java/com/czertainly/api/model/connector/notification/NotificationDataStatusChange.java
  src/main/java/com/czertainly/api/model/connector/notification/NotificationDataText.java
  src/main/java/com/czertainly/api/model/connector/notification/NotificationType.java
Labels: enhancement, ignore-for-release

#285 Add endpoints for assigning approval profile to RA profile
  src/main/java/com/czertainly/api/interfaces/core/web/AuthorityInstanceController.java
  src/main/java/com/czertainly/api/interfaces/core/web/RAProfileManagementController.java
Labels: new-feature

#288 Implement management of notification instances
  src/main/java/com/czertainly/api/interfaces/core/web/NotificationInstanceController.java
  src/main/java/com/czertainly/api/model/core/audit/ObjectType.java
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
Labels: new-feature

#289 Update approval DTOs and notification data
  src/main/java/com/czertainly/api/exception/ValidationException.java
  src/main/java/com/czertainly/api/interfaces/core/web/RAProfileManagementController.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileRelationDto.java
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/connector/notification/NotificationDataScheduledJobCompleted.java
  src/main/java/com/czertainly/api/model/connector/notification/NotificationDataStatusChange.java
  src/main/java/com/czertainly/api/model/connector/notification/NotificationDataText.java
  src/main/java/com/czertainly/api/model/connector/notification/NotificationType.java
  src/main/java/com/czertainly/api/model/connector/notification/data/NotificationDataApproval.java
  src/main/java/com/czertainly/api/model/connector/notification/data/NotificationDataCertificateStatusChanged.java
  src/main/java/com/czertainly/api/model/connector/notification/data/NotificationDataScheduledJobCompleted.java
  src/main/java/com/czertainly/api/model/connector/notification/data/NotificationDataStatusChanged.java
  src/main/java/com/czertainly/api/model/connector/notification/data/NotificationDataText.java
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
Labels: enhancement, ignore-for-release

#292 Fix certificate status change notification data to mark RA profile optional
  src/main/java/com/czertainly/api/model/connector/notification/data/NotificationDataCertificateStatusChanged.java
  src/main/java/com/czertainly/api/model/core/audit/ObjectType.java
  src/main/java/com/czertainly/api/model/core/audit/OperationType.java
Labels: bug, ignore-for-release

#291 Add notifications settings endpoints
  src/main/java/com/czertainly/api/interfaces/core/web/SettingController.java
  src/main/java/com/czertainly/api/model/core/settings/NotificationSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/SettingsSection.java
Labels: new-feature
