Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2023-01, with the labels that each got.

#143 Add listing endpoint to key management interface
  src/main/java/com/czertainly/api/clients/cryptography/KeyManagementApiClient.java
  src/main/java/com/czertainly/api/interfaces/connector/cryptography/KeyManagementController.java
Labels: enhancement

#144 Key type support
  src/main/java/com/czertainly/api/clients/cryptography/CryptographicOperationsApiClient.java
  src/main/java/com/czertainly/api/clients/cryptography/KeyManagementApiClient.java
  src/main/java/com/czertainly/api/interfaces/connector/cryptography/CryptographicOperationsController.java
  src/main/java/com/czertainly/api/interfaces/connector/cryptography/KeyManagementController.java
  src/main/java/com/czertainly/api/interfaces/connector/cryptography/TokenInstanceController.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/KeyFormat.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/KeyType.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/KeyData.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/KeyDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/KeyPairDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/PrivateKeyDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/PublicKeyDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/SecretKeyDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/value/KeyValue.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/value/RawKeyValue.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/value/SpkiKeyValue.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/CipherDataRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/SignatureDataRequestDto.java
Labels: enhancement

#147 Separate the abstract class from KeyValue
  src/main/java/com/czertainly/api/model/connector/cryptography/key/value/AbstractKeyValue.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/value/KeyValue.java
Labels: enhancement, ignore-for-release

#148 Add Certificate UUID to Discovery and Fix Audit controller
  src/main/java/com/czertainly/api/interfaces/core/web/AuditLogController.java
  src/main/java/com/czertainly/api/model/core/discovery/DiscoveryCertificatesDto.java
Labels: enhancement

#149 Add missing Types to the Base Attributes
  src/main/java/com/czertainly/api/interfaces/core/web/CustomAttributeController.java
  src/main/java/com/czertainly/api/model/client/attribute/BaseAttributeDto.java
  src/main/java/com/czertainly/api/model/core/auth/ResourceDto.java
Labels: bug

#150 Set Deserialization on Unknown Properties as false
  src/main/java/com/czertainly/api/config/serializer/ResponseAttributeSerializer.java
Labels: bug

#152 Cryptographic Provider Core Interface
  src/main/java/com/czertainly/api/exception/NotFoundException.java
  src/main/java/com/czertainly/api/interfaces/core/web/CallbackController.java
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicKeyController.java
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicOperationsController.java
  src/main/java/com/czertainly/api/interfaces/core/web/GroupController.java
  src/main/java/com/czertainly/api/interfaces/core/web/TokenInstanceController.java
  src/main/java/com/czertainly/api/interfaces/core/web/TokenProfileController.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/BulkKeyUsageRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/EditKeyRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/KeyRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/KeyRequestType.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/UpdateKeyUsageRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/operations/CipherDataRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/operations/RandomDataRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/operations/SignDataRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/operations/VerifyDataRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/token/TokenInstanceRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/tokenprofile/AddTokenProfileRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/tokenprofile/BulkTokenProfileKeyUsageRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/tokenprofile/EditTokenProfileRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/tokenprofile/TokenProfileKeyUsageRequestDto.java
  src/main/java/com/czertainly/api/model/core/audit/ObjectType.java
  src/main/java/com/czertainly/api/model/core/audit/OperationType.java
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyEvent.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyEventHistoryDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyEventStatus.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyItemDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyState.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyUsage.java
  src/main/java/com/czertainly/api/model/core/cryptography/token/TokenInstanceDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/token/TokenInstanceDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/token/TokenInstanceStatusDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/tokenprofile/TokenProfileDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/tokenprofile/TokenProfileDto.java
  src/main/java/com/czertainly/core/util/CryptographicHelper.java
Labels: new-feature

#156 Add resources to the DTO when Creating and Updating Custom Attributes
  src/main/java/com/czertainly/api/model/client/attribute/custom/CustomAttributeCreateRequestDto.java
  src/main/java/com/czertainly/api/model/client/attribute/custom/CustomAttributeUpdateRequestDto.java
Labels: enhancement

#157 Fix callback Path for the callback controller
  src/main/java/com/czertainly/api/interfaces/core/web/CallbackController.java
Labels: bug, ignore-for-release

#155 Update Java and Spring/Hibernate to new version
  .github/workflows/build.yml
  pom.xml
  src/main/java/com/czertainly/api/clients/BaseApiClient.java
Labels: enhancement

#161 Move Signature Attributes and Cipher Attributes to Core
  src/main/java/com/czertainly/api/clients/cryptography/CryptographicOperationsApiClient.java
  src/main/java/com/czertainly/api/interfaces/connector/cryptography/CryptographicOperationsController.java
  src/main/java/com/czertainly/api/model/common/collection/DigestAlgorithm.java
  src/main/java/com/czertainly/api/model/common/collection/RsaSignatureScheme.java
Labels: enhancement

#162 Add endpoints for the management of individual custom attributes per objects
  src/main/java/com/czertainly/api/interfaces/core/web/CustomAttributeController.java
  src/main/java/com/czertainly/api/model/client/certificate/UploadCertificateRequestDto.java
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
Labels: enhancement

#163 Add equals and hashcode for certificate dto from connector
  src/main/java/com/czertainly/api/model/connector/discovery/DiscoveryProviderCertificateDataDto.java
Labels: bug

#164 Add JsonCreator and JsonValue to the Cryptography Enums
  src/main/java/com/czertainly/api/model/client/attribute/BaseAttributeContentDto.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/BaseAttributeContent.java
  src/main/java/com/czertainly/api/model/common/collection/DigestAlgorithm.java
  src/main/java/com/czertainly/api/model/common/collection/RsaSignatureScheme.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/CryptographicAlgorithm.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/KeyFormat.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/KeyType.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/TokenInstanceStatus.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/KeyData.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyUsage.java
Labels: enhancement

#165 Add Kind to Token and Token details DTO
  src/main/java/com/czertainly/api/model/core/certificate/CertificateType.java
  src/main/java/com/czertainly/api/model/core/cryptography/token/TokenInstanceDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/token/TokenInstanceDto.java
Labels: enhancement

#166 Consolidate POM dependencies between project with help of parent POM file #158
  .github/workflows/build.yml
  pom.xml
Labels: enhancement

#168 Fix Schema for ACME and Key Details
  src/main/java/com/czertainly/api/model/client/raprofile/RaProfileAcmeDetailResponseDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDetailDto.java
Labels: bug

#169 Update schema for cryptographic Keys
  src/main/java/com/czertainly/api/model/client/cryptography/key/EditKeyRequestDto.java
  src/main/java/com/czertainly/api/model/client/raprofile/RaProfileAcmeDetailResponseDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDetailDto.java
Labels: bug
