Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2023-04, with the labels that each got.

#216 Add search filters for discoveries inventory with support for pagination
  src/main/java/com/czertainly/api/interfaces/core/web/DiscoveryController.java
  src/main/java/com/czertainly/api/model/client/certificate/DiscoveryResponseDto.java
  src/main/java/com/czertainly/api/model/core/discovery/DiscoveryStatus.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFieldType.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: enhancement

#217 Fix deserializing of FileAttributeContentData
  pom.xml
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/FileAttributeContentData.java
  src/main/java/com/czertainly/core/util/V2AttributeMigrationUtils.java
Labels: bug

#219 Add search filters for locations inventory with support for pagination
  src/main/java/com/czertainly/api/interfaces/core/web/LocationManagementController.java
  src/main/java/com/czertainly/api/model/client/certificate/LocationsResponseDto.java
Labels: enhancement

#223 Define common interface and structure for platform enums
  src/main/java/com/czertainly/api/interfaces/core/web/EnumController.java
  src/main/java/com/czertainly/api/model/client/certificate/SearchFilterRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/KeyCompromiseReason.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/KeyRequestType.java
  src/main/java/com/czertainly/api/model/common/HealthStatus.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/AttributeType.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/callback/AttributeValueTarget.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/constraint/AttributeConstraintType.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/AttributeContentType.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/ProgrammingLanguageEnum.java
  src/main/java/com/czertainly/api/model/common/enums/IPlatformEnum.java
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/CryptographicAlgorithm.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/IAbstractSearchableEnum.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/KeyFormat.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/KeyType.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/TokenInstanceStatus.java
  src/main/java/com/czertainly/api/model/core/acme/AccountStatus.java
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateStatus.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateType.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateValidationStatus.java
  src/main/java/com/czertainly/api/model/core/compliance/ComplianceRuleStatus.java
  src/main/java/com/czertainly/api/model/core/compliance/ComplianceStatus.java
  src/main/java/com/czertainly/api/model/core/connector/AuthType.java
  src/main/java/com/czertainly/api/model/core/connector/ConnectorStatus.java
  src/main/java/com/czertainly/api/model/core/connector/FunctionGroupCode.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyState.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyUsage.java
  src/main/java/com/czertainly/api/model/core/discovery/DiscoveryStatus.java
  src/main/java/com/czertainly/api/model/core/enums/EnumItemDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchCondition.java
  src/main/java/com/czertainly/api/model/core/search/SearchFieldDataByGroupDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchFieldDataDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchGroup.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFieldType.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
  src/main/java/com/czertainly/api/model/core/settings/SettingsSection.java
Labels: enhancement

#226 SCEP updates and Intune implementation
  src/main/java/com/czertainly/api/exception/ScepException.java
  src/main/java/com/czertainly/api/interfaces/core/scep/ScepController.java
  src/main/java/com/czertainly/api/interfaces/core/scep/ScepRaProfileController.java
  src/main/java/com/czertainly/api/model/client/scep/BaseScepProfileRequestDto.java
  src/main/java/com/czertainly/api/model/common/collection/DigestAlgorithm.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/RsaPadding.java
  src/main/java/com/czertainly/api/model/core/scep/FailInfo.java
  src/main/java/com/czertainly/api/model/core/scep/MessageType.java
  src/main/java/com/czertainly/api/model/core/scep/PkiStatus.java
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDetailDto.java
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDto.java
  src/main/java/com/czertainly/api/model/core/scep/ScepRequestMessage.java
  src/main/java/com/czertainly/api/model/core/scep/ScepResponseMessage.java
Labels: new-feature

#228 Include MD5 in the digest algorithm
  src/main/java/com/czertainly/api/model/common/collection/DigestAlgorithm.java
Labels: ignore-for-release
