Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2023-06, with the labels that each got.

#252 Update Audit logs listing response pagination to return total items count
  src/main/java/com/czertainly/api/model/core/audit/AuditLogResponseDto.java
Labels: bug

#254 Update version to 2.8.0 and README
  README.md
  pom.xml
Labels: ignore-for-release

#249 Change owner of certificate to user reference
  src/main/java/com/czertainly/api/model/client/certificate/CertificateUpdateObjectsDto.java
  src/main/java/com/czertainly/api/model/client/certificate/MultipleCertificateObjectUpdateDto.java
Labels: enhancement

#256 Change response of enable/disable operation for scheduled jobs
  src/main/java/com/czertainly/api/interfaces/core/web/ScepProfileController.java
  src/main/java/com/czertainly/api/interfaces/core/web/SchedulerController.java
Labels: bug, ignore-for-release

#258 Fix enable/disable operation to reflect result of operation in Scheduler service
  src/main/java/com/czertainly/api/clients/SchedulerApiClient.java
  src/main/java/com/czertainly/api/exception/SchedulerException.java
  src/main/java/com/czertainly/api/interfaces/core/web/DiscoveryController.java
  src/main/java/com/czertainly/api/interfaces/core/web/SchedulerController.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduleDiscoveryDto.java
Labels: bug

#259 Fix enable/disable operation to reflect result of operation in Scheduler service
  src/main/java/com/czertainly/api/clients/SchedulerApiClient.java
Labels: ignore-for-release

#260 Add error message and last execution status to scheduled job DTOs
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobHistoryDto.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerJobExecutionStatus.java
Labels: enhancement, ignore-for-release

#261 Add result to scheduled job history to reference created discovery
  src/main/java/com/czertainly/api/interfaces/core/web/DiscoveryController.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduleDiscoveryDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobDetailDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobHistoryDto.java
Labels: enhancement, ignore-for-release

#264 New SearchableFields item with name "PRIVATE_KEY"
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: enhancement, ignore-for-release

#265 Add reference to source certificate in certificate detail
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDetailDto.java
Labels: enhancement

#267 Add issue and revoke attributes to certificate
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDetailDto.java
Labels: enhancement

#268 Add list of related certificates to certificate detail DTO
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDetailDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateEvent.java
Labels: enhancement, ignore-for-release

#271 Define interface for management of approval profiles
  src/main/java/com/czertainly/api/interfaces/core/web/ApprovalProfileController.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileDetailDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileRequestDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileResponseDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileUpdateRequestDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalStepDto.java
Labels: new-feature

#272 Fix discovery certificate pagination
  pom.xml
  src/main/java/com/czertainly/api/model/connector/discovery/DiscoveryDataRequestDto.java
Labels: bug
