Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2023-02, with the labels that each got.

#174 Renew and Rekey Certificate Implementation
  src/main/java/com/czertainly/api/interfaces/core/client/v2/ClientOperationController.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateRekeyRequestDto.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateRenewRequestDto.java
Labels: enhancement

#175 Add Validation of Custom Attribute
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicKeyController.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/AttributeContentType.java
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
Labels: enhancement

#176 Implement search on cryptographic keys
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicKeyController.java
  src/main/java/com/czertainly/api/model/client/cryptography/CryptographicKeyResponseDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchLabelConstants.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: enhancement

#177 Fix validation of attributes
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
Labels: bug

#178 Add configuration for trusted certificates
  pom.xml
  src/main/java/com/czertainly/api/clients/BaseApiClient.java
  src/main/java/com/czertainly/config/TrustedCertificatesConfig.java
  src/main/java/com/czertainly/core/util/CertificateUtil.java
Labels: enhancement

#180 Bug fixes and APIs for the Keys
  src/main/java/com/czertainly/api/clients/cryptography/KeyManagementApiClient.java
  src/main/java/com/czertainly/api/exception/AcmeProblemDocumentException.java
  src/main/java/com/czertainly/api/exception/AlreadyExistException.java
  src/main/java/com/czertainly/api/exception/ValidationException.java
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicKeyController.java
  src/main/java/com/czertainly/api/model/client/cryptography/CryptographicKeyResponseDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/KeyCompromiseReason.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyItemDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyItemDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/tokenprofile/TokenProfileDto.java
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
Labels: bug, enhancement, ignore-for-release

#179 Add CodeBlock attribute content type
  src/main/java/com/czertainly/api/model/client/attribute/BaseAttributeContentDto.java
  src/main/java/com/czertainly/api/model/client/attribute/RequestAttributeDto.java
  src/main/java/com/czertainly/api/model/client/attribute/ResponseAttributeDto.java
  src/main/java/com/czertainly/api/model/common/attribute/v1/AttributeType.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/CustomAttribute.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/DataAttribute.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/InfoAttribute.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/MetadataAttribute.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/AttributeContentType.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/CodeBlockAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/CodeBlockAttributeContentData.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/ProgrammingLanguageEnum.java
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
  src/main/java/com/czertainly/core/util/V2AttributeMigrationUtils.java
Labels: enhancement

#181 Add more filter conditions to cryptography keys search and fix non functioning filters
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/CryptographicAlgorithm.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/IAbstractSearchableEnum.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/KeyFormat.java
  src/main/java/com/czertainly/api/model/connector/cryptography/enums/KeyType.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyState.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyUsage.java
  src/main/java/com/czertainly/api/model/core/search/SearchLabelConstants.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: enhancement

#182 Add CodeBlock attribute content type - added missing constructor
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/CodeBlockAttributeContentData.java
Labels: bug

#183 Fix codeblock content type content validation
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/BaseAttributeContent.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/CodeBlockAttributeContent.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFieldType.java
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
  src/test/java/com/czertainly/util/AttributeDefinitionUtilsTest.java
Labels: bug

#184 Split Certificate List and Detail DTO
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/model/client/certificate/CertificateResponseDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDetailDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
Labels: enhancement

#185 Add API to retrieve the certificate content
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateContentDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDetailDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
Labels: enhancement

#186 Remove CSR attributes from rekey request
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateRekeyRequestDto.java
Labels: enhancement

#187 Fix sonarqube issues
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/BaseAttributeContent.java
Labels: bug, ignore-for-release

#190 Rewrite certificates filtering with predicates based on cryptographic keys filtering
  src/main/java/com/czertainly/api/model/core/certificate/CertificateStatus.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateValidationStatus.java
  src/main/java/com/czertainly/api/model/core/compliance/ComplianceStatus.java
  src/main/java/com/czertainly/api/model/core/search/SearchLabelConstants.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: enhancement

#191 Add platform settings management endpoints
  src/main/java/com/czertainly/api/interfaces/core/web/SettingController.java
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
  src/main/java/com/czertainly/api/model/core/setting/AllSettingsDto.java
  src/main/java/com/czertainly/api/model/core/setting/GeneralSettingsDto.java
  src/main/java/com/czertainly/api/model/core/setting/Section.java
  src/main/java/com/czertainly/api/model/core/setting/SectionDto.java
  src/main/java/com/czertainly/api/model/core/setting/SectionSettingsDto.java
Labels: enhancement

#192 Generalize ACME protocol endpoints
  src/main/java/com/czertainly/api/interfaces/core/acme/AcmeController.java
  src/main/java/com/czertainly/api/interfaces/core/acme/AcmeRaProfileController.java
  src/main/java/com/czertainly/api/model/core/acme/AcmeProfileDto.java
  src/main/java/com/czertainly/api/model/core/acme/AcmeProfileListDto.java
  src/main/java/com/czertainly/api/model/core/acme/Challenge.java
  src/main/java/com/czertainly/api/model/core/acme/Directory.java
  src/main/java/com/czertainly/api/model/core/acme/KeyRollover.java
  src/main/java/com/czertainly/api/model/core/acme/Order.java
Labels: enhancement

#195 Simplify settings management and update DTOs
  src/main/java/com/czertainly/api/interfaces/core/web/SettingController.java
  src/main/java/com/czertainly/api/model/client/attribute/custom/CustomAttributeCreateRequestDto.java
  src/main/java/com/czertainly/api/model/client/attribute/custom/CustomAttributeUpdateRequestDto.java
  src/main/java/com/czertainly/api/model/client/attribute/metadata/GlobalMetadataCreateRequestDto.java
  src/main/java/com/czertainly/api/model/client/attribute/metadata/GlobalMetadataUpdateRequestDto.java
  src/main/java/com/czertainly/api/model/core/setting/GeneralSettingsDto.java
  src/main/java/com/czertainly/api/model/core/setting/SectionSettingsDto.java
Labels: enhancement, ignore-for-release
