Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2023-05, with the labels that each got.

#229 Update custom attributes listing DTO
  src/main/java/com/czertainly/api/interfaces/core/web/CustomAttributeController.java
  src/main/java/com/czertainly/api/model/client/attribute/custom/CustomAttributeDefinitionDto.java
Labels: enhancement

#230 Implement interface to communicate with Scheduler service
  src/main/java/com/czertainly/api/clients/CzertainlyBaseApiClient.java
  src/main/java/com/czertainly/api/clients/SchedulerApiClient.java
  src/main/java/com/czertainly/api/exception/ConnectionServiceException.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerJobDetail.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerJobExecutionMessage.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerJobExecutionStatus.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerJobHistory.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerRequestDto.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerResponseDto.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerStatus.java
Labels: new-feature

#234 Add SCEP URL to listing DTO
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDetailDto.java
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDto.java
Labels: enhancement, ignore-for-release

#235 SCEP challenge password optional
  src/main/java/com/czertainly/api/model/client/scep/BaseScepProfileRequestDto.java
Labels: ignore-for-release

#238 Add endpoint to issue existing certificate in status New
  src/main/java/com/czertainly/api/interfaces/core/client/v2/ClientOperationController.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateSignRequestDto.java
Labels: enhancement

#245 Change sign data as required in sign data request DTO
  src/main/java/com/czertainly/api/model/client/cryptography/operations/SignDataRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/SignDataRequestDto.java
  src/main/java/com/czertainly/api/model/connector/cryptography/operations/SignatureDataRequestDto.java
Labels: bug, ignore-for-release

#247 Rename Key state enum item Compromised destroyed
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyState.java
Labels: enhancement, ignore-for-release

#248 Add web interface for management of scheduled jobs
  src/main/java/com/czertainly/api/clients/SchedulerApiClient.java
  src/main/java/com/czertainly/api/interfaces/core/web/DiscoveryController.java
  src/main/java/com/czertainly/api/interfaces/core/web/SchedulerController.java
  src/main/java/com/czertainly/api/model/core/audit/ObjectType.java
  src/main/java/com/czertainly/api/model/core/audit/OperationType.java
  src/main/java/com/czertainly/api/model/core/scheduler/PaginationRequestDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/PaginationResponseDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobDetailDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobHistoryDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobHistoryResponseDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobsResponseDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/SchedulerJobInfoDto.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerJobDto.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerJobExecutionMessage.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerJobHistory.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerRequestDto.java
  src/main/java/com/czertainly/api/model/scheduler/SchedulerResponseDto.java
Labels: new-feature
