Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2023-03, with the labels that each got.

#196 Delete SearchLabelConstants and transfer the functionality into Core
  src/main/java/com/czertainly/api/model/core/search/SearchLabelConstants.java
Labels: ignore-for-release

#199 Support searching and filtering on metadata and custom attributes
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/model/client/certificate/SearchFilterRequestDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchFieldDataByGroupDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchFieldDataDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchGroup.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFieldType.java
Labels: enhancement

#201 Update properties names of search fields DTOs
  src/main/java/com/czertainly/api/model/client/certificate/SearchFilterRequestDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchFieldDataByGroupDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchFieldDataDto.java
Labels: enhancement, ignore-for-release

#203 Change settings implementation to not use attributes
  src/main/java/com/czertainly/api/interfaces/core/web/SettingController.java
  src/main/java/com/czertainly/api/model/core/setting/AllSettingsDto.java
  src/main/java/com/czertainly/api/model/core/setting/SectionDto.java
  src/main/java/com/czertainly/api/model/core/setting/SectionSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/PlatformSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/Section.java
  src/main/java/com/czertainly/api/model/core/settings/UtilsSettingsDto.java
Labels: ignore-for-release

#205 Fix certificate DTO schema regarding New status of certificate (CSR)
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
Labels: bug, ignore-for-release

#206 Add support for searching in metadata and custom attributes content
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/model/client/certificate/SearchFilterRequestDto.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/AttributeContentType.java
  src/main/java/com/czertainly/api/model/core/search/SearchGroup.java
Labels: enhancement, ignore-for-release

#207 Add certificate custom attribute when issuing a certificate to location
  src/main/java/com/czertainly/api/model/client/location/IssueToLocationRequestDto.java
Labels: enhancement, ignore-for-release

#208 Update search group label
  src/main/java/com/czertainly/api/model/core/search/SearchFieldDataDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchGroup.java
Labels: ignore-for-release

#209 Add endpoint for user identification
  src/main/java/com/czertainly/api/interfaces/core/web/UserManagementController.java
  src/main/java/com/czertainly/api/model/client/auth/UserIdentificationRequestDto.java
Labels: enhancement

#210 Rename Legacy Client Operation DTOs
  src/main/java/com/czertainly/api/interfaces/core/client/ClientOperationController.java
  src/main/java/com/czertainly/api/model/client/authority/LegacyClientCertificateRevocationDto.java
  src/main/java/com/czertainly/api/model/client/authority/LegacyClientCertificateSignRequestDto.java
Labels: documentation, ignore-for-release

#212 Update release version to 2.7.0
  pom.xml
Labels: ignore-for-release

#213 Add endpoints for SCEP Protocol and management of SCEP profiles
  pom.xml
  src/main/java/com/czertainly/api/interfaces/core/scep/ScepController.java
  src/main/java/com/czertainly/api/interfaces/core/scep/ScepRaProfileController.java
  src/main/java/com/czertainly/api/interfaces/core/web/RAProfileManagementController.java
  src/main/java/com/czertainly/api/interfaces/core/web/ScepProfileController.java
  src/main/java/com/czertainly/api/model/client/raprofile/ActivateScepForRaProfileRequestDto.java
  src/main/java/com/czertainly/api/model/client/raprofile/RaProfileScepDetailResponseDto.java
  src/main/java/com/czertainly/api/model/client/scep/BaseScepProfileRequestDto.java
  src/main/java/com/czertainly/api/model/client/scep/ScepProfileEditRequestDto.java
  src/main/java/com/czertainly/api/model/client/scep/ScepProfileRequestDto.java
  src/main/java/com/czertainly/api/model/core/audit/ObjectType.java
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
  src/main/java/com/czertainly/api/model/core/scep/FailInfo.java
  src/main/java/com/czertainly/api/model/core/scep/PkiStatus.java
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDetailDto.java
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDto.java
  src/main/java/com/czertainly/api/model/core/scep/ScepRequestMessage.java
  src/main/java/com/czertainly/api/model/core/scep/ScepResponseMessage.java
Labels: new-feature

#215 Add endpoint to list certificates eligible as CA certificate for SCEP
  src/main/java/com/czertainly/api/interfaces/core/web/ScepProfileController.java
Labels: enhancement, ignore-for-release
