Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2023-11, with the labels that each got.

#325 Add identify endpoint to Authority certificate V2 interface
  src/main/java/com/czertainly/api/clients/v2/CertificateApiClient.java
  src/main/java/com/czertainly/api/interfaces/connector/v2/CertificateController.java
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/model/client/certificate/CertificateUpdateObjectsDto.java
  src/main/java/com/czertainly/api/model/client/certificate/MultipleCertificateObjectUpdateDto.java
  src/main/java/com/czertainly/api/model/connector/v2/CertificateDataResponseDto.java
  src/main/java/com/czertainly/api/model/connector/v2/CertificateIdentificationRequestDto.java
  src/main/java/com/czertainly/api/model/connector/v2/CertificateIdentificationResponseDto.java
Labels: new-feature

#329 Update protocol profiles DTOs and key DTOs with UUIDs of related objects
  src/main/java/com/czertainly/api/model/client/acme/AcmeAccountListResponseDto.java
  src/main/java/com/czertainly/api/model/client/acme/AcmeAccountResponseDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/EditKeyRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/KeyRequestDto.java
  src/main/java/com/czertainly/api/model/core/acme/AcmeProfileDto.java
  src/main/java/com/czertainly/api/model/core/acme/AcmeProfileListDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyItemDto.java
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDetailDto.java
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDto.java
Labels: enhancement, ignore-for-release

#330 Update release version to 2.10.0
  pom.xml
Labels: ignore-for-release

#327 Add an option to mark CA certificate as trusted
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/model/client/certificate/CertificateUpdateObjectsDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchCondition.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: new-feature

#333 Add endpoint to get the issuer's certificates for authority instance
  src/main/java/com/czertainly/api/clients/AuthorityInstanceApiClient.java
  src/main/java/com/czertainly/api/interfaces/connector/AuthorityInstanceController.java
  src/main/java/com/czertainly/api/model/connector/authority/CaCertificatesRequestDto.java
  src/main/java/com/czertainly/api/model/connector/authority/CaCertificatesResponseDto.java
Labels: new-feature
