Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2023-10, with the labels that each got.

#317 Add certificate chain download endpoint
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateChainDownloadResponseDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateChainResponseDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateFormat.java
Labels: enhancement

#319 Refactor endpoints related to certificate validation
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateValidationCheck.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateValidationDto.java
Labels: refactoring

#320 Change get certificate validation result endpoint DTO
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateValidationCheck.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateValidationCheckDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateValidationResultDto.java
Labels: bug, ignore-for-release

#322 Replace certificate status with certificate state and validation status
  src/main/java/com/czertainly/api/model/client/dashboard/StatisticsDto.java
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/connector/notification/NotificationType.java
  src/main/java/com/czertainly/api/model/core/authority/CertificateRevocationReason.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateEvent.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateState.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateValidationResultDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateValidationStatus.java
  src/main/java/com/czertainly/api/model/core/compliance/ComplianceStatus.java
  src/main/java/com/czertainly/api/model/core/location/CertificateInLocationDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateRenewRequestDto.java
Labels: new-feature
