Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2024-04, with the labels that each got.

#360 Add endpoints to list filter fields usable in rule conditions and rule actions
  src/main/java/com/czertainly/api/interfaces/core/web/ResourceController.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: new-feature

#362 Add endpoint for retrieving event for resource
  src/main/java/com/czertainly/api/interfaces/core/web/ResourceController.java
  src/main/java/com/czertainly/api/model/client/discovery/DiscoveryDto.java
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/core/rules/ResourceEvent.java
  src/main/java/com/czertainly/api/model/core/rules/RuleActionType.java
Labels: new-feature, ignore-for-release

#367 Update DTOs for rules and triggers
  src/main/java/com/czertainly/api/interfaces/core/web/RuleController.java
  src/main/java/com/czertainly/api/model/core/rules/RuleActionGroupDetailDto.java
  src/main/java/com/czertainly/api/model/core/rules/RuleActionGroupDto.java
  src/main/java/com/czertainly/api/model/core/rules/RuleActionGroupRequestDto.java
  src/main/java/com/czertainly/api/model/core/rules/RuleConditionGroupDetailDto.java
  src/main/java/com/czertainly/api/model/core/rules/RuleConditionGroupDto.java
  src/main/java/com/czertainly/api/model/core/rules/RuleConditionGroupRequestDto.java
  src/main/java/com/czertainly/api/model/core/rules/RuleRequestDto.java
  src/main/java/com/czertainly/api/model/core/rules/RuleTriggerDto.java
  src/main/java/com/czertainly/api/model/core/rules/RuleTriggerRequestDto.java
  src/main/java/com/czertainly/api/model/core/rules/UpdateRuleRequestDto.java
  src/main/java/com/czertainly/api/model/core/rules/UpdateRuleTriggerRequestDto.java
Labels: ignore-for-release, refactoring

#366 Add request format to authority provider DTOs
  src/main/java/com/czertainly/api/model/connector/v2/CertificateRenewRequestDto.java
  src/main/java/com/czertainly/api/model/connector/v2/CertificateSignRequestDto.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateRenewRequestDto.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateRequestDto.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateSignRequestDto.java
Labels: enhancement

#368 Add CertificateRequestException
  src/main/java/com/czertainly/api/exception/CertificateRequestException.java
  src/main/java/com/czertainly/api/interfaces/connector/v2/CertificateController.java
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
Labels: enhancement
