Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2024-05, with the labels that each got.

#369 Add CRMF support for rekey requests
  src/main/java/com/czertainly/api/interfaces/core/client/v2/ClientOperationController.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateRekeyRequestDto.java
Labels: enhancement

#370 Add constructors to client renew, rekey request
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateRekeyRequestDto.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateRenewRequestDto.java
Labels: bug, ignore-for-release

#371 Add resources listing and update resource event listing response
  src/main/java/com/czertainly/api/interfaces/core/web/AuthController.java
  src/main/java/com/czertainly/api/interfaces/core/web/ResourceController.java
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/core/auth/AuthResourceDto.java
  src/main/java/com/czertainly/api/model/core/auth/ResourceDetailDto.java
  src/main/java/com/czertainly/api/model/core/other/ResourceDto.java
  src/main/java/com/czertainly/api/model/core/other/ResourceEvent.java
  src/main/java/com/czertainly/api/model/core/other/ResourceEventDto.java
Labels: enhancement

#373 Add util method to create attribute content from string
  src/main/java/com/czertainly/api/model/core/rules/RuleTriggerDto.java
  src/main/java/com/czertainly/api/model/core/rules/RuleTriggerRequestDto.java
  src/main/java/com/czertainly/api/model/core/rules/UpdateRuleTriggerRequestDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
Labels: enhancement, ignore-for-release

#374 Add associated triggers to Discovery detail DTO
  src/main/java/com/czertainly/api/model/client/discovery/DiscoveryHistoryDetailDto.java
  src/main/java/com/czertainly/api/model/core/rules/UpdateRuleTriggerRequestDto.java
Labels: enhancement, ignore-for-release

#375 Add list of groups UUIDs in certificate, keys and users DTOs to allow assigning multiple groups
  src/main/java/com/czertainly/api/model/client/auth/AddUserRequestDto.java
  src/main/java/com/czertainly/api/model/client/auth/UpdateUserRequestDto.java
  src/main/java/com/czertainly/api/model/client/certificate/CertificateUpdateObjectsDto.java
  src/main/java/com/czertainly/api/model/client/certificate/MultipleCertificateObjectUpdateDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/EditKeyRequestDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/KeyRequestDto.java
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
  src/main/java/com/czertainly/api/model/core/auth/UserDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserRequestDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserUpdateRequestDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyItemDto.java
  src/main/java/com/czertainly/api/model/core/other/ResourceDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: enhancement

#380 Change type of creation timestamp property used in DTOs
  src/main/java/com/czertainly/api/model/core/audit/AuditLogDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateEventHistoryDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyEventHistoryDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyItemDto.java
Labels: enhancement, ignore-for-release

#381 Add workflow resources to Resource enum
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
Labels: enhancement

#382 Add endpoint to get trigger history summary
  src/main/java/com/czertainly/api/interfaces/core/web/TriggerController.java
  src/main/java/com/czertainly/api/model/core/workflows/TriggerHistoryDto.java
  src/main/java/com/czertainly/api/model/core/workflows/TriggerHistoryObjectSummaryDto.java
  src/main/java/com/czertainly/api/model/core/workflows/TriggerHistoryObjectTriggerSummaryDto.java
  src/main/java/com/czertainly/api/model/core/workflows/TriggerHistoryRecordDto.java
  src/main/java/com/czertainly/api/model/core/workflows/TriggerHistorySummaryDto.java
Labels: enhancement, ignore-for-release

#383 Fix switching of name and description in @Schema in TriggerHistoryRecordDto
  src/main/java/com/czertainly/api/model/core/workflows/TriggerHistoryRecordDto.java
Labels: bug, ignore-for-release

#384 Add Processing Discovery status
  src/main/java/com/czertainly/api/model/core/discovery/DiscoveryStatus.java
Labels: enhancement

#385 Fix attributes constructors to use correct AttributeType in parent constructor
  src/main/java/com/czertainly/api/model/common/attribute/v2/CustomAttribute.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/InfoAttribute.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/MetadataAttribute.java
Labels: bug
