Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2024-02, with the labels that each got.

#347 Add enabled property to KeyRequestDto
  src/main/java/com/czertainly/api/model/client/cryptography/key/KeyRequestDto.java
Labels: enhancement

#346 Update search field identifier description to inform how to get identifier
  src/main/java/com/czertainly/api/model/client/certificate/SearchFilterRequestDto.java
Labels: documentation

#349 Update release version to 2.11.0
  pom.xml
Labels: ignore-for-release
