Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2024-01, with the labels that each got.

#340 Add endpoint to retrieve CA certificate chain for RA profile
  src/main/java/com/czertainly/api/interfaces/core/web/RAProfileManagementController.java
Labels: new-feature, ignore-for-release

#342 Update descriptions of certificate update DTOs
  src/main/java/com/czertainly/api/model/client/certificate/CertificateUpdateObjectsDto.java
  src/main/java/com/czertainly/api/model/client/certificate/MultipleCertificateObjectUpdateDto.java
Labels: documentation, ignore-for-release

#343 Correct Swagger annotation schema for some platform enums
  src/main/java/com/czertainly/api/model/connector/notification/NotificationType.java
  src/main/java/com/czertainly/api/model/core/authority/CertificateRevocationReason.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateFormat.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateFormatEncoding.java
  src/main/java/com/czertainly/api/model/core/enums/CertificateRequestFormat.java
Labels: bug, ignore-for-release

#344 Fix equals method of BaseAttributeContent
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/BaseAttributeContent.java
Labels: bug
