Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2024-06, with the labels that each got.

#387 Release version 2.12.0
  pom.xml
Labels: ignore-for-release

#391 Add new constructor to CmpCrmfValidationException
  src/main/java/com/czertainly/api/interfaces/core/cmp/error/CmpCrmfValidationException.java
Labels: enhancement, ignore-for-release

#392 Make request and response protection method required in CmpProfileDetailDto
  src/main/java/com/czertainly/api/model/core/cmp/CmpProfileDetailDto.java
Labels: bug, ignore-for-release

#393 Update dependency versions and actions
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/publish-package.yml
  .github/workflows/workflow_run_pruner.yml
  pom.xml
  src/main/java/com/czertainly/api/exception/MessageHandlingException.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalDetailDto.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalDetailStepDto.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalResponseDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileDetailDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileResponseDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalStepDto.java
  src/main/java/com/czertainly/api/model/client/discovery/DiscoveryHistoryDetailDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationRequestDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationResponseDto.java
  src/main/java/com/czertainly/api/model/client/raprofile/RaProfileAcmeDetailResponseDto.java
  src/main/java/com/czertainly/api/model/client/raprofile/RaProfileScepDetailResponseDto.java
  src/main/java/com/czertainly/api/model/client/scep/ScepProfileRequestDto.java
  src/main/java/com/czertainly/api/model/connector/notification/NotificationProviderInstanceDto.java
  src/main/java/com/czertainly/api/model/core/audit/AuditLogResponseDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateChainDownloadResponseDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyAssociationDto.java
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDetailDto.java
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobHistoryResponseDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/ScheduledJobsResponseDto.java
Labels: enhancement
