Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2024-11, with the labels that each got.

#415 Updates to release 2.13.1
  pom.xml
Labels: ignore-for-release

#414 Update audit logs model and DTOs to use common log record structure
  pom.xml
  src/main/java/com/czertainly/api/interfaces/core/client/v2/ClientOperationController.java
  src/main/java/com/czertainly/api/interfaces/core/web/AuditLogController.java
  src/main/java/com/czertainly/api/model/client/attribute/AttributeDefinitionDto.java
  src/main/java/com/czertainly/api/model/client/auth/AddUserRequestDto.java
  src/main/java/com/czertainly/api/model/client/certificate/SearchRequestDto.java
  src/main/java/com/czertainly/api/model/client/connector/ConnectorRequestDto.java
  src/main/java/com/czertainly/api/model/common/NameAndUuidDto.java
  src/main/java/com/czertainly/api/model/common/UuidDto.java
  src/main/java/com/czertainly/api/model/common/enums/IPlatformEnum.java
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/core/audit/AuditLogDto.java
  src/main/java/com/czertainly/api/model/core/audit/AuditLogFilter.java
  src/main/java/com/czertainly/api/model/core/audit/EventTypeEnum.java
  src/main/java/com/czertainly/api/model/core/audit/ObjectType.java
  src/main/java/com/czertainly/api/model/core/audit/OperationStatusEnum.java
  src/main/java/com/czertainly/api/model/core/audit/OperationType.java
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
  src/main/java/com/czertainly/api/model/core/auth/UserDetailDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
  src/main/java/com/czertainly/api/model/core/logging/Loggable.java
  src/main/java/com/czertainly/api/model/core/logging/enums/ActorType.java
  src/main/java/com/czertainly/api/model/core/logging/enums/AuthMethod.java
  src/main/java/com/czertainly/api/model/core/logging/enums/Module.java
  src/main/java/com/czertainly/api/model/core/logging/enums/Operation.java
  src/main/java/com/czertainly/api/model/core/logging/enums/OperationResult.java
  src/main/java/com/czertainly/api/model/core/logging/records/ActorRecord.java
  src/main/java/com/czertainly/api/model/core/logging/records/LogRecord.java
  src/main/java/com/czertainly/api/model/core/logging/records/ResourceRecord.java
  src/main/java/com/czertainly/api/model/core/logging/records/SourceRecord.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateDataResponseDto.java
Labels: enhancement

#413 Implement endpoints for OAuth2 provider management
  src/main/java/com/czertainly/api/interfaces/core/web/SettingController.java
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
  src/main/java/com/czertainly/api/model/core/logging/Sensitive.java
  src/main/java/com/czertainly/api/model/core/settings/AuthenticationSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/AuthenticationSettingsUpdateDto.java
  src/main/java/com/czertainly/api/model/core/settings/NotificationSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/OAuth2ProviderSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/SettingsSection.java
  src/main/java/com/czertainly/api/model/core/settings/SettingsSectionCategory.java
Labels: new-feature
