Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2024-09, with the labels that each got.

#407 Updates to release 2.13.0
  .github/workflows/build.yml
  README.md
  pom.xml
Labels: ignore-for-release

#409 Clean up code related to filtering
  src/main/java/com/czertainly/api/exception/NotSupportedException.java
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
  src/main/java/com/czertainly/api/interfaces/core/web/LocationManagementController.java
  src/main/java/com/czertainly/api/model/client/certificate/SearchFilterRequestDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchFieldDataDto.java
  src/main/java/com/czertainly/api/model/core/search/SearchableFields.java
Labels: ignore-for-release, refactoring

#410 Increase version number
  pom.xml
Labels: dependencies, ignore-for-release

#411 Add attribute content data class to AttributeContentType enum
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/AttributeContentType.java
Labels: enhancement

#412 Add Certificate Subject type enum
  src/main/java/com/czertainly/api/model/client/dashboard/StatisticsDto.java
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDetailDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateSubjectType.java
Labels: enhancement
