Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2025-09, with the labels that each got.

#528 Move CryptographicHelper to Core
  src/main/java/com/czertainly/core/util/CryptographicHelper.java
Labels: ignore-for-release, refactoring

#536 Add endpoints for handling compliance internal rules
  src/main/java/com/czertainly/api/interfaces/core/web/v2/ComplianceProfileController.java
  src/main/java/com/czertainly/api/model/client/compliance/v2/ComplianceInternalRuleRequestDto.java
  src/main/java/com/czertainly/api/model/common/enums/IPlatformEnum.java
  src/main/java/com/czertainly/api/model/core/compliance/ComplianceRuleStatus.java
  src/main/java/com/czertainly/api/model/core/compliance/ComplianceStatus.java
  src/main/java/com/czertainly/api/model/core/compliance/v2/ComplianceRuleDto.java
  src/main/java/com/czertainly/api/model/core/compliance/v2/ComplianceRuleListDto.java
Labels: enhancement, ignore-for-release

#535 Refactor LogRecord resource to unify UUID and name of resource objects under one record instead of separate lists
  src/main/java/com/czertainly/api/model/core/logging/records/LogRecord.java
  src/main/java/com/czertainly/api/model/core/logging/records/ResourceObjectIdentity.java
  src/main/java/com/czertainly/api/model/core/logging/records/ResourceRecord.java
  src/main/java/com/czertainly/api/model/core/settings/logging/AuditLoggingSettingsDto.java
Labels: enhancement

#538 Add timestamp to AuditLogDto
  src/main/java/com/czertainly/api/model/core/audit/AuditLogDto.java
Labels: enhancement, ignore-for-release

#541 Add validation to Attribute Content Data classes
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/AttributeContentData.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/CodeBlockAttributeContentData.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/CredentialAttributeContentData.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/FileAttributeContentData.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/content/data/SecretAttributeContentData.java
  src/main/java/com/czertainly/core/util/AttributeDefinitionUtils.java
Labels: enhancement
