Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2025-02, with the labels that each got.

#428 Add attribute version
  src/main/java/com/czertainly/api/model/client/attribute/BaseAttributeDto.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/AbstractBaseAttribute.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/BaseAttribute.java
Labels: enhancement

#429 Remove token instance from key management endpoints path and link key with certificate request
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicKeyController.java
  src/main/java/com/czertainly/api/model/common/enums/cryptography/KeyAlgorithm.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateRequestDto.java
Labels: enhancement

#430 Hide duplicated parent properties in OpenAPI schema of AuditLoggingSettingsDto
  src/main/java/com/czertainly/api/model/core/settings/logging/AuditLoggingSettingsDto.java
Labels: bug

#432 Add endpoint for editing cryptographic key item
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicKeyController.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/EditKeyItemDto.java
Labels: enhancement

#434 Add constructor to NotificationDto
  src/main/java/com/czertainly/api/model/client/notification/NotificationDto.java
Labels: enhancement, ignore-for-release

#435 Remove NotNull validation from Utils Service URL in platform settings
  src/main/java/com/czertainly/api/model/core/settings/UtilsSettingsDto.java
Labels: bug, ignore-for-release

#436 Remove disable action from Approval profiles
  src/main/java/com/czertainly/api/interfaces/core/web/ApprovalProfileController.java
Labels: enhancement

#437 Make revoke certificate request in Certificate API v1 as blocking
  src/main/java/com/czertainly/api/clients/CertificateApiClient.java
Labels: bug

#438 Rename ActionDto from auth package to AuthActionDto
  src/main/java/com/czertainly/api/model/core/auth/AuthActionDto.java
  src/main/java/com/czertainly/api/model/core/auth/AuthResourceDto.java
Labels: refactoring

#439 Add additional endpoints for keys management without token instance
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicKeyController.java
Labels: enhancement, ignore-for-release

#440 Make token profile UUID not required in EditKeyRequestDto
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicKeyController.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/EditKeyRequestDto.java
Labels: ignore-for-release

#441 Add compromise and destroy key endpoint without token instance
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicKeyController.java
Labels: enhancement, ignore-for-release
