Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2025-03, with the labels that each got.

#444 Update OpenAPI for Token Instance Management
  src/main/java/com/czertainly/api/interfaces/core/web/TokenInstanceController.java
Labels: documentation, ignore-for-release

#445 Updates to release 2.14.1
  pom.xml
Labels: ignore-for-release

#446 Release version 2.14.1
  pom.xml
  src/main/java/com/czertainly/api/clients/CertificateApiClient.java
  src/main/java/com/czertainly/api/interfaces/core/web/ApprovalProfileController.java
  src/main/java/com/czertainly/api/interfaces/core/web/CryptographicKeyController.java
  src/main/java/com/czertainly/api/interfaces/core/web/TokenInstanceController.java
  src/main/java/com/czertainly/api/model/client/attribute/BaseAttributeDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/EditKeyItemDto.java
  src/main/java/com/czertainly/api/model/client/cryptography/key/EditKeyRequestDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationDto.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/AbstractBaseAttribute.java
  src/main/java/com/czertainly/api/model/common/attribute/v2/BaseAttribute.java
  src/main/java/com/czertainly/api/model/common/enums/cryptography/KeyAlgorithm.java
  src/main/java/com/czertainly/api/model/core/auth/AuthActionDto.java
  src/main/java/com/czertainly/api/model/core/auth/AuthResourceDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateRequestDto.java
  src/main/java/com/czertainly/api/model/core/settings/UtilsSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/authentication/OAuth2ProviderSettingsUpdateDto.java
  src/main/java/com/czertainly/api/model/core/settings/logging/AuditLoggingSettingsDto.java
Labels: ignore-for-release

#448 Raise version of CZERTAINLY Interfaces
  pom.xml
Labels: ignore-for-release

#450 Fix KeyValue subtypes schema to omit abstract parent schema
  src/main/java/com/czertainly/api/config/OpenApiConfig.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/value/KeyValue.java
  src/main/java/com/czertainly/api/model/connector/cryptography/key/value/KeyValueDto.java
Labels: bug, ignore-for-release

#449 Add list of JWK set keys to OAuth2 Provider Settings
  src/main/java/com/czertainly/api/model/core/settings/authentication/JwkDto.java
  src/main/java/com/czertainly/api/model/core/settings/authentication/OAuth2ProviderSettingsDto.java
Labels: enhancement

#451 Refactor Certificate Validation Settings Dtos
  src/main/java/com/czertainly/api/interfaces/core/web/RAProfileManagementController.java
  src/main/java/com/czertainly/api/interfaces/core/web/SettingController.java
  src/main/java/com/czertainly/api/model/core/raprofile/RaProfileCertificateValidationSettingsDto.java
  src/main/java/com/czertainly/api/model/core/raprofile/RaProfileCertificateValidationSettingsUpdateDto.java
  src/main/java/com/czertainly/api/model/core/raprofile/RaProfileDto.java
  src/main/java/com/czertainly/api/model/core/raprofile/RaProfileValidationUpdateDto.java
  src/main/java/com/czertainly/api/model/core/settings/CertificateSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/CertificateSettingsUpdateDto.java
  src/main/java/com/czertainly/api/model/core/settings/CertificateValidationSettingsUpdateDto.java
  src/main/java/com/czertainly/api/model/core/settings/PlatformSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/PlatformSettingsUpdateDto.java
Labels: ignore-for-release, refactoring

#453 Do not allow null frequency and expiring threshold for enabled certificate validation
  src/main/java/com/czertainly/api/model/core/raprofile/RaProfileCertificateValidationSettingsUpdateDto.java
  src/main/java/com/czertainly/api/model/core/settings/CertificateValidationSettingsUpdateDto.java
Labels: ignore-for-release, refactoring

#454 Add info and health endpoints
  src/main/java/com/czertainly/api/interfaces/AuthProtectedController.java
  src/main/java/com/czertainly/api/interfaces/core/web/InfoController.java
  src/main/java/com/czertainly/api/model/core/info/ActuatorHealthDto.java
  src/main/java/com/czertainly/api/model/core/info/AppInfoDto.java
  src/main/java/com/czertainly/api/model/core/info/CoreInfoResponseDto.java
  src/main/java/com/czertainly/api/model/core/info/DatabaseInfoDto.java
Labels: enhancement

#457 Fix validation of RA Profile Certificate Validation Settings
  src/main/java/com/czertainly/api/model/core/raprofile/RaProfileCertificateValidationSettingsUpdateDto.java
Labels: bug, ignore-for-release
