Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2025-05, with the labels that each got.

#472 Add notification profiles management endpoints and DTOs
  src/main/java/com/czertainly/api/exception/EventException.java
  src/main/java/com/czertainly/api/interfaces/core/web/ApprovalProfileController.java
  src/main/java/com/czertainly/api/interfaces/core/web/NotificationProfileController.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationProfileDetailDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationProfileDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationProfileRequestDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationProfileResponseDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationProfileUpdateRequestDto.java
  src/main/java/com/czertainly/api/model/client/notification/RecipientDto.java
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
  src/main/java/com/czertainly/api/model/core/notification/RecipientType.java
Labels: new-feature

#476 Fix isInternalNotificationPossible condition for NotificationProfileUpdateRequestDto
  src/main/java/com/czertainly/api/model/client/notification/NotificationProfileUpdateRequestDto.java
Labels: bug

#477 Change execution item for send notification execution type
  src/main/java/com/czertainly/api/interfaces/core/web/ActionController.java
  src/main/java/com/czertainly/api/model/core/workflows/ExecutionItemDto.java
  src/main/java/com/czertainly/api/model/core/workflows/ExecutionItemRequestDto.java
Labels: ignore-for-release

#478 Add events associations and settings endpoints
  src/main/java/com/czertainly/api/interfaces/core/web/SettingController.java
  src/main/java/com/czertainly/api/interfaces/core/web/TriggerController.java
  src/main/java/com/czertainly/api/model/core/settings/EventSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/EventsSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/NotificationSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/SettingsSection.java
  src/main/java/com/czertainly/api/model/core/workflows/TriggerEventAssociationRequestDto.java
Labels: new-feature

#479 Fix constructors of event settings DTOs
  src/main/java/com/czertainly/api/model/core/settings/EventSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/EventsSettingsDto.java
Labels: ignore-for-release

#482 Add Default recipient type for notification profiles
  src/main/java/com/czertainly/api/interfaces/core/web/SettingController.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationProfileDetailDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationProfileDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationProfileUpdateRequestDto.java
  src/main/java/com/czertainly/api/model/common/events/data/ApprovalEventData.java
  src/main/java/com/czertainly/api/model/common/events/data/CertificateActionPerformedEventData.java
  src/main/java/com/czertainly/api/model/common/events/data/CertificateDiscoveredEventData.java
  src/main/java/com/czertainly/api/model/common/events/data/CertificateStatusChangedEventData.java
  src/main/java/com/czertainly/api/model/common/events/data/DiscoveryFinishedEventData.java
  src/main/java/com/czertainly/api/model/common/events/data/ScheduledJobFinishedEventData.java
  src/main/java/com/czertainly/api/model/core/notification/RecipientType.java
  src/main/java/com/czertainly/api/model/core/other/ResourceEvent.java
  src/main/java/com/czertainly/api/model/core/settings/EventSettingsDto.java
  src/main/java/com/czertainly/api/model/core/settings/EventsSettingsDto.java
Labels: enhancement, ignore-for-release
