Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2025-08, with the labels that each got.

#512 Change UUID parameters in CertificateController from String to UUID
  src/main/java/com/czertainly/api/interfaces/core/web/CertificateController.java
Labels: bug, ignore-for-release

#513 Add archived property to CertificateDto
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
Labels: enhancement, ignore-for-release

#514 Add protocol certificate associations DTO to related protocol profiles DTOs
  src/main/java/com/czertainly/api/interfaces/core/web/AcmeProfileController.java
  src/main/java/com/czertainly/api/interfaces/core/web/ScepProfileController.java
  src/main/java/com/czertainly/api/model/client/acme/AcmeAccountResponseDto.java
  src/main/java/com/czertainly/api/model/client/acme/AcmeProfileEditRequestDto.java
  src/main/java/com/czertainly/api/model/client/acme/AcmeProfileRequestDto.java
  src/main/java/com/czertainly/api/model/client/cmp/BaseCmpProfileRequestDto.java
  src/main/java/com/czertainly/api/model/client/scep/BaseScepProfileRequestDto.java
  src/main/java/com/czertainly/api/model/core/acme/AcmeProfileDto.java
  src/main/java/com/czertainly/api/model/core/cmp/CmpProfileDetailDto.java
  src/main/java/com/czertainly/api/model/core/cmp/CmpProfileDto.java
  src/main/java/com/czertainly/api/model/core/protocol/ProtocolCertificateAssociationsDto.java
  src/main/java/com/czertainly/api/model/core/scep/ScepProfileDetailDto.java
Labels: new-feature

#521 Add Get Associations Operation to log retrieving associations
  src/main/java/com/czertainly/api/model/core/logging/enums/Operation.java
Labels: ignore-for-release

#525 Add Pending Certificate Relation Type
  src/main/java/com/czertainly/api/model/core/certificate/CertificateRelationType.java
Labels: enhancement, ignore-for-release

#526 Add Certificate Relation Type to Platform Enum
  src/main/java/com/czertainly/api/model/common/enums/PlatformEnum.java
Labels: enhancement, ignore-for-release
