Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2025-04, with the labels that each got.

#460 Add listing permissions to user profile DTO
  src/main/java/com/czertainly/api/model/core/auth/UserProfileDetailDto.java
  src/main/java/com/czertainly/api/model/core/auth/UserProfilePermissionsDto.java
Labels: enhancement

#461 Update user profile endpoint response DTO
  src/main/java/com/czertainly/api/interfaces/core/web/AuthController.java
Labels: enhancement, ignore-for-release

#463 Fix response DTOs schemas to correct required mode of properties
  src/main/java/com/czertainly/api/model/client/acme/AcmeAccountListResponseDto.java
  src/main/java/com/czertainly/api/model/client/acme/AcmeAccountResponseDto.java
  src/main/java/com/czertainly/api/model/client/approval/ApprovalStepRecipientDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileDto.java
  src/main/java/com/czertainly/api/model/core/authority/AuthorityInstanceDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDetailDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateEventHistoryDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateRequestDto.java
  src/main/java/com/czertainly/api/model/core/credential/CredentialDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyItemDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/key/KeyItemDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/token/TokenInstanceDetailDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/token/TokenInstanceDto.java
  src/main/java/com/czertainly/api/model/core/cryptography/tokenprofile/TokenProfileDto.java
  src/main/java/com/czertainly/api/model/core/entity/EntityInstanceDto.java
  src/main/java/com/czertainly/api/model/core/raprofile/RaProfileDto.java
Labels: bug

#464 Fix query params wrapped as object to be generated as separate params in OpenAPI
  pom.xml
  src/main/java/com/czertainly/api/model/client/approval/ApprovalUserDto.java
  src/main/java/com/czertainly/api/model/client/approvalprofile/ApprovalProfileForVersionDto.java
  src/main/java/com/czertainly/api/model/client/notification/NotificationRequestDto.java
  src/main/java/com/czertainly/api/model/core/scheduler/PaginationRequestDto.java
Labels: bug

#468 Update KeyAlgorithm enum with NIST standardized PQC algorithms
  src/main/java/com/czertainly/api/model/common/enums/cryptography/KeyAlgorithm.java
Labels: enhancement

#469 Fix Rekey Certificate request body schema
  src/main/java/com/czertainly/api/interfaces/core/client/v2/ClientOperationController.java
  src/main/java/com/czertainly/api/model/core/v2/ClientCertificateRekeyRequestDto.java
Labels: bug
