Repository CZERTAINLY/CZERTAINLY-Interfaces, pull requests merged in 2025-06, with the labels that each got.

#484 Add Any resource to use in rules and actions
  src/main/java/com/czertainly/api/model/core/auth/Resource.java
Labels: enhancement

#488 Override equals and hashCode methods in BaseAttribute
  src/main/java/com/czertainly/api/model/common/attribute/v2/BaseAttribute.java
Labels: ignore-for-release

#490 Validate frequency in Notification Profile to only contain days and hours
  src/main/java/com/czertainly/api/model/client/notification/NotificationProfileUpdateRequestDto.java
  src/main/java/com/czertainly/api/model/client/notification/validation/FrequencyValidator.java
  src/main/java/com/czertainly/api/model/client/notification/validation/ValidFrequency.java
Labels: enhancement, ignore-for-release

#491 Update release version to 2.15.0
  pom.xml
Labels: ignore-for-release

#492 Fix required schema of certificate and certificate request alternative key properties
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
  src/main/java/com/czertainly/api/model/core/certificate/CertificateRequestDto.java
Labels: bug

#493 Update version to 2.15.1-SNAPSHOT
  pom.xml
Labels: ignore-for-release

#494 Fix signature algorithm property of CertificateDto and make it not required
  src/main/java/com/czertainly/api/model/core/certificate/CertificateDto.java
Labels: bug

#496 Fix notification profile frequency constraint validator to accept not set frequency
  src/main/java/com/czertainly/api/model/client/notification/validation/FrequencyValidator.java
Labels: bug
